version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gibster:password@db:5432/gibster
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=development-secret-key-change-in-production
      - ENCRYPTION_KEY=development-encryption-key-change-in-production
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  worker:
    build: .
    command: python run_worker.py
    environment:
      - DATABASE_URL=postgresql://gibster:password@db:5432/gibster
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=development-secret-key-change-in-production
      - ENCRYPTION_KEY=development-encryption-key-change-in-production
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=gibster
      - POSTGRES_USER=gibster
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: 