"""Add SyncJobLog table for observability

Revision ID: 03fd6815538f
Revises: 
Create Date: 2025-07-01 16:05:26.251124

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03fd6815538f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_job_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sync_job_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sync_job_id"],
            ["sync_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_job_logs_sync_job_id"),
        "sync_job_logs",
        ["sync_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_job_logs_timestamp"), "sync_job_logs", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_job_logs_timestamp"), table_name="sync_job_logs")
    op.drop_index(op.f("ix_sync_job_logs_sync_job_id"), table_name="sync_job_logs")
    op.drop_table("sync_job_logs")
    # ### end Alembic commands ###
