apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gibster-cert
  namespace: gibster
spec:
  secretName: gibster-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ${PRODUCTION_DOMAIN}
  dnsNames:
    - ${PRODUCTION_DOMAIN}
    - www.${PRODUCTION_DOMAIN}