apiVersion: apps/v1
kind: Deployment
metadata:
  name: gibster-frontend
  namespace: gibster
  labels:
    app: gibster
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gibster
      component: frontend
  template:
    metadata:
      labels:
        app: gibster
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gibster-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: gibster-config
              key: api-url
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: gibster-frontend
  namespace: gibster
  labels:
    app: gibster
    component: frontend
spec:
  selector:
    app: gibster
    component: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP