apiVersion: v1
kind: Secret
metadata:
  name: gibster-secrets
  namespace: gibster
  labels:
    app: gibster
type: Opaque
stringData:
  database-url: "postgresql://gibster:CHANGE_ME@postgres-cluster-rw.database.svc.cluster.local:5432/gibster"
  secret-key: "CHANGE_ME_TO_SECURE_KEY"
  encryption-key: "CHANGE_ME_TO_SECURE_ENCRYPTION_KEY"
  redis-password: "CHANGE_ME_TO_REDIS_PASSWORD"
  s3-access-key: "CHANGE_ME_TO_S3_ACCESS_KEY"
  s3-secret-key: "CHANGE_ME_TO_S3_SECRET_KEY"